version: 0.0
os: linux
files:
  - source: app/index.html
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: app/before_install.sh
      timeout: 180
  ApplicationStart:
    - location: app/application_start.sh
      timeout: 180
  ValidateService:
    - location: app/validate_service.sh
      timeout: 180
